---
- name: Set up web server on Amazon Linux EC2
  hosts: all
  become: true
  gather_facts: yes

  tasks:

    - name: Install NGINX and PHP
      yum:
        name:
          - nginx
          - php
          - php-mysqlnd
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy index.php
      copy:
        src: ./index.php
        dest: /usr/share/nginx/html/index.php
        mode: '0644'

    - name: Copy submit.php
      copy:
        src: ./submit.php
        dest: /usr/share/nginx/html/submit.php
        mode: '0644'

    - name: Wait for NGINX to be available
      wait_for:
        port: 80
        delay: 5
        timeout: 120
        state: started

    - name: Debug - Deployed
      debug:
        msg: "NGINX and PHP installed, web files copied"
