name: Deploy Infra and Configure EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform + Ansible Deployment
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: |
          cd terraform
          terraform init


      - name: Wait for AWS resources cleanup
        run: sleep 20

      - name: Terraform Plan and Apply
        run: |
          cd terraform
          terraform plan -out=tfplan
          terraform validate  
          terraform apply -auto-approve tfplan

      - name: Export EC2 public IP (safe)
        run: |
          IP=$(terraform output -raw public_ip || echo "")
          echo "EC2_IP=$IP" >> "$GITHUB_ENV"
        

      - name: Export EC2 IP
        run: |
           echo "EC2_IP=$(terraform output -raw public_ip)" >> "$GITHUB_ENV"
        

      - name: Save EC2 IP for Ansible
        run: |
          echo "[web]" > ../inventory.ini
          echo "$EC2_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ../inventory.ini

  ansible:
    name: Ansible Configuration
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    working-directory: ./ansible
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Copy SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Ping server
        run: ansible all -i ../inventory.ini -m ping

      - name: Run Playbook
        run: ansible-playbook -i ../inventory.ini deploy.yaml
    
  
      


    

      