name: Deploy Infra and Configure EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Terraform + Ansible Deployment
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Format
        run: |
          cd terraform
          ls -la
          ls  

      - name: Terraform Init & Apply
        run: |
          cd terraform
          terraform init
          terraform plan -out=tfplan
          terraform validate  
          terraform apply -auto-approve

      

      - name: Get EC2 public IP
        id: get_ip
        run: |
          echo "EC2_IP=$(terraform output -raw public_ip)" >> "$GITHUB_ENV"

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Create Inventory File
        run: |
          echo "[web]" > inventory
          echo "$EC2_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory ansible/playbook.yml
